# justfile — 项目入口任务，本地 + CI 共用
# Generated by init-ci skill (recipe: A-lightweight)

default: ci

# 完整 CI 流水线（本地 commit / push 前 / GitHub Actions 都跑这套）
ci: lint typecheck test

lint:
    uv run ruff check .
    uv run ruff format --check .

typecheck:
    uv run pyright

test:
    uv run pytest

# 本地：自动修复 lint / format
fix:
    uv run ruff check --fix .
    uv run ruff format .

# 本地：首次 setup（装环境 + 装 hook）
setup:
    uv sync --all-extras
    uv run pre-commit install --hook-type pre-commit --hook-type pre-push
