# justfile — 项目入口任务，本地 + CI 共用
# Generated by init-ci skill (recipe: A-lightweight), customized for TradingAgents-CN fork.
#
# ⚠️ 工具调用策略：
# - lint / typecheck / format（ruff、pyright）→ `uvx`（从 pypi 拉，本地 + CI 同源，
#   无需把 ruff/pyright 加进 pyproject 依赖）
# - test（pytest）→ `uv run --no-sync`（pytest 在 .venv，pyproject 依赖里）
# - 用 --no-sync 因上游 uv.lock 与 pyproject 不同步 + qianfan@3.13 不可解，默认
#   `uv run` 会触发 universal resolution 失败。假设 venv 已就位（CI 在前置 step 装好；
#   本地见 docs/USAGE.md「一次性环境搭建」段）。

default: ci

# 完整 CI 流水线（本地 commit / push 前 / GitHub Actions 都跑这套）
ci: lint typecheck test

lint:
    uvx ruff check .
    uvx ruff format --check .

typecheck:
    uvx pyright

test:
    uv run --no-sync pytest

# 本地：自动修复 lint / format
fix:
    uvx ruff check --fix .
    uvx ruff format .

# 本地：首次 setup（装 pre-commit hook）
# 注：venv 创建 + 依赖安装见 docs/USAGE.md，不用 `uv sync --all-extras`（qianfan 问题）
setup:
    uvx pre-commit install --hook-type pre-commit --hook-type pre-push
