# justfile — 项目入口任务，本地 + CI 共用
# Generated by init-ci skill (recipe: A-lightweight), customized for TradingAgents-CN fork.
#
# ⚠️ 工具调用策略：
# - lint / typecheck / format（ruff、pyright）→ `uvx`（从 pypi 拉，本地 + CI 同源，
#   无需把 ruff/pyright 加进 pyproject 依赖）
# - test（pytest）→ `uv run --no-sync`（pytest 在 .venv，pyproject 依赖里）
# - 用 --no-sync 因上游 uv.lock 与 pyproject 不同步 + qianfan@3.13 不可解，默认
#   `uv run` 会触发 universal resolution 失败。假设 venv 已就位（CI 在前置 step 装好；
#   本地见 docs/USAGE.md「一次性环境搭建」段）。

default: ci

# 完整 CI 流水线（本地 commit / push 前 / GitHub Actions 都跑这套）
ci: lint typecheck test

lint:
    uvx ruff check .
    uvx ruff format --check .

typecheck:
    uvx pyright

test:
    #!/usr/bin/env bash
    # pytest exit 5 = "no tests collected"，对 -m unit 在 unit 标记 0 个时是合法情况
    set -uo pipefail
    uv run --no-sync pytest -m unit
    status=$?
    [ $status -eq 0 ] || [ $status -eq 5 ]

# 本地：自动修复 lint / format
fix:
    uvx ruff check --fix .
    uvx ruff format .

# 本地：首次 setup（装 pre-commit hook）
# 注：venv 创建 + 依赖安装见 docs/USAGE.md，不用 `uv sync --all-extras`（qianfan 问题）
setup:
    uvx pre-commit install --hook-type pre-commit --hook-type pre-push

# ────────────────────────────────────────────────────────────────────────────
# 本地开发栈启停（thin wrapper 调 scripts/dev.sh，详见该脚本 --help）
# ────────────────────────────────────────────────────────────────────────────

# 启全栈（原生 mongo+redis + backend uvicorn + frontend vite）
up:
    scripts/dev.sh start

# 停全栈
down:
    scripts/dev.sh stop

# 重启全栈
dev-restart:
    scripts/dev.sh restart

# 端口/进程/服务状态
status:
    scripts/dev.sh status

# tail backend 日志（Ctrl-C 退出）
logs:
    scripts/dev.sh logs backend

# tail frontend 日志
logs-frontend:
    scripts/dev.sh logs frontend

# ────────────────────────────────────────────────────────────────────────────
# Binding / port 审计（OpenSpec change `binding-audit-tooling` 沉淀）
# 见 openspec/specs/audit-tooling/spec.md
# ────────────────────────────────────────────────────────────────────────────

# 端口审计：扫所有 5430x 端口的 LISTEN 状态 + 标记非 127.0.0.1 binding
audit-ports:
    #!/usr/bin/env bash
    set -uo pipefail
    echo "=== 5430x 端口 LISTEN 状态 ==="
    PORTS=$(lsof -nP -iTCP -sTCP:LISTEN 2>/dev/null | awk 'NR==1 || $9 ~ /:5430[0-9]$/')
    if [ "$(echo "$PORTS" | wc -l)" -le 1 ]; then
        echo "  (无 5430x 端口监听 — 服务未启动？)"
        exit 0
    fi
    echo "$PORTS"
    echo ""
    echo "=== 违规检查 (绑 * / 0.0.0.0 = 违反 loopback 规定) ==="
    VIOLATIONS=$(echo "$PORTS" | awk 'NR>1 && ($9 ~ /^\*:5430[0-9]$/ || $9 ~ /^0\.0\.0\.0:5430[0-9]$/)')
    if [ -n "$VIOLATIONS" ]; then
        echo "$VIOLATIONS" | sed 's/^/  ⚠️  /'
        echo ""
        echo "上述端口绑非 127.0.0.1，违反 CLAUDE.md「项目特殊约定」loopback 规定"
        exit 1
    fi
    echo "  ✓ 全部端口绑 127.0.0.1 合规"

# Binding 配置审计：fork-local 配置文件中检查 0.0.0.0 hardcode + 上游端口违规
# 不扫 .env（gitignored，本地各异）
audit-binds:
    #!/usr/bin/env bash
    set -uo pipefail
    EXIT_CODE=0

    echo "=== 1. 0.0.0.0 hardcode 在 fork-local 配置文件 ==="
    BAD=$(grep -nE '"0\.0\.0\.0"' frontend/vite.config.ts 2>/dev/null || true)
    if [ -n "$BAD" ]; then
        echo "$BAD" | sed 's/^/  ⚠️  /'
        EXIT_CODE=1
    else
        echo "  ✓ frontend/vite.config.ts 无 0.0.0.0 hardcode"
    fi
    echo ""

    echo "=== 2. config/mongod.conf 和 config/redis.conf 必须 bind 127.0.0.1 ==="
    if [ -f config/mongod.conf ]; then
        if grep -qE "bindIp:\s*127\.0\.0\.1" config/mongod.conf; then
            echo "  ✓ config/mongod.conf: bindIp 127.0.0.1"
        else
            echo "  ⚠️  config/mongod.conf: bindIp 不是 127.0.0.1"
            EXIT_CODE=1
        fi
        if grep -qE "port:\s*54302" config/mongod.conf; then
            echo "  ✓ config/mongod.conf: port 54302"
        else
            echo "  ⚠️  config/mongod.conf: port 不是 54302"
            EXIT_CODE=1
        fi
    else
        echo "  (config/mongod.conf 不存在 — 首次部署请运行 ./scripts/setup-native.sh)"
    fi
    if [ -f config/redis.conf ]; then
        if grep -qE "^bind\s+127\.0\.0\.1" config/redis.conf; then
            echo "  ✓ config/redis.conf: bind 127.0.0.1"
        else
            echo "  ⚠️  config/redis.conf: bind 不是 127.0.0.1"
            EXIT_CODE=1
        fi
        if grep -qE "^port\s+54303" config/redis.conf; then
            echo "  ✓ config/redis.conf: port 54303"
        else
            echo "  ⚠️  config/redis.conf: port 不是 54303"
            EXIT_CODE=1
        fi
    fi
    echo ""

    echo "=== 3. vite.config.ts 必须用 fork-local 端口 (54300) + loopback host ==="
    if [ -f frontend/vite.config.ts ]; then
        if ! grep -qE "host:\s*['\"]127\.0\.0\.1['\"]" frontend/vite.config.ts; then
            echo "  ⚠️  frontend/vite.config.ts 缺 host: '127.0.0.1' 配置"
            EXIT_CODE=1
        fi
        if ! grep -qE "port:\s*54300" frontend/vite.config.ts; then
            echo "  ⚠️  frontend/vite.config.ts 缺 port: 54300 配置"
            EXIT_CODE=1
        fi
        if grep -qE "target:\s*['\"]http://(localhost|127\.0\.0\.1):8000" frontend/vite.config.ts; then
            echo "  ⚠️  frontend/vite.config.ts proxy.target 仍指向 :8000（应 :54301）"
            EXIT_CODE=1
        fi
        [ $EXIT_CODE -eq 0 ] && echo "  ✓ vite.config.ts host/port/proxy 配置合规"
    fi
    echo ""

    if [ $EXIT_CODE -eq 0 ]; then
        echo "✅ Binding 审计全过"
    else
        echo "❌ Binding 审计有违规项（见上）"
    fi
    exit $EXIT_CODE
